config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  root 'welcome#index'
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :create, :update]

  resources :listings do
  resources :reservations 
  end
  # post "/admin/user/:id/listings" => "listing#admin_create", as: admin_listing
  resources :admin, only: [:index, :show]

  get  "/reservations/:id/braintree/new" => "braintree#new", as: "braintree_new"
  post "/reservations/:id/braintree/checkout" => "braintree#checkout", as: "braintree_checkout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :users
	has_many :reservations
	has_many :users, through: :reservation
	mount_uploader :avatar, AvatarUploader
end

app/models/listings_user.rb
class ListingsUser < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  	belongs_to :user
  	belongs_to :listing

  	validate :overlap?, on: :create

    def duration
      (self.check_out - self.check_in).to_i
    end

    def total_price
      self.duration * self.listing.price
    end

  	private
  	def overlap?
  		self.listing.reservations.each do |x|
  			i = (x.check_in..x.check_out).to_a
  			o = (check_in..check_out).to_a	
  			unless (i & o).empty?	
  				errors.add(:overlap, "overlap")
  				break
  			end
  		end
	end
end

app/models/user.rb
Clearance::User

class User < ApplicationRecord
  include Clearance::User
 has_many :authentications, dependent: :destroy
 has_many :listings
 has_many :reservations

  mount_uploader :avatar, AvatarUploader
 
 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     email: auth_hash["extra"]["raw_info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab fb_token to access Facebook for user data
 def fb_token
   x = self.authentications.find_by(provider: 'facebook')
   return x.token unless x.nil?
 end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_user
	before_action :check_admin
	def index
		@listing = Listing.all
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def check_user
		if !current_user
		redirect_to root_path, notice: "No trespassing. "
		end
	end

	def check_admin
		if !current_user.admin
		redirect_to root_path, notice: "No trespassing."
		end
	end
end

app/controllers/application_controller.rb
Clearance::Controller

class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception 

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	@reservation = Reservation.find(params[:id])
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
  @reservation = Reservation.find(params[:id])

  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => @reservation.total_price,
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    redirect_to "/users/#{current_user.id}", :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :check_user
	before_action :check_admin
	def index
		@listing = Listing.order(:name).page(params[:page])
		@smoking = Listing.where(smoking_allowed:true).page(params[:page])
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def new
		@new_list = current_user.listings.new
	end	

	def create
		@new_list = current_user.listings.new(allowed_params)
			if @new_list.save
				redirect_to "/users/#{current_user.id}"
			else
				render "new"
			end
	end

	def edit
		@listings = Listing.find(params[:id])	
	end

	def update
		@listings = Listing.find(params[:id])
			if @listings.update_attributes(allowed_params)
			@listings.update(edit_params)
				redirect_to "/users/#{current_user.id}"
			else
				render "new"
			end		
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy	
		redirect_to "/users/#{current_user.id}"
	end

	private
		def allowed_params
		params.require(:listing).permit(:name, :property_type, :room_number, :bed_number, :guest_number, :country, :state, :city, :zipcode, :address, :price, :description, :user_id, :smoking_allowed, :avatar)
		end

	private
		def edit_params
		params.require(:listing).permit(:avatar)
		end

	def check_user
		if !current_user
			flash[:notice] = "Sorry, please sign in to continue!"
			redirect_to sign_in_path
		end 
	end

	def check_admin
		if current_user.admin
			redirect_to admin_index_path
		end
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	
	def index
		@reservation = Reservation.all
		@listing = Listing.all
		@reserved_listing = @listing.find_by(@reservation.id)
	end

	def show
	end

	def new
		@listing = Listing.find(params[:listing_id])
		@new_reservation = Reservation.new
	end

	def create
		@listing = Listing.find(params[:listing_id])
		@new_reservation = Reservation.new(allowed_params)
		@new_reservation.user_id = current_user.id
		@new_reservation.listing_id = @listing.id 
			if @new_reservation.save
				redirect_to braintree_new_path(@new_reservation)
			else
				render "new"
			end		
	end

	private
		def allowed_params
		params.require(:reservation).permit(:check_in, :check_out, :user_id, :listing_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    authentication.update_token(auth_hash)
    @next = root_url
    @notice = "Signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    @next = edit_user_path(user)
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to @next, :notice => @notice
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@user_listing = @user.listings
		@user_reservation = @user.reservations
	end

	def create
	end

	def update
		@user = User.find(params[:id])
		@user.update(edit_params)
		redirect_to @user
	end

	private
	def edit_params
		params.require(:user).permit(:avatar)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/new.html.erb
<div class="demo-frame">

  <%= form_for :checkout_form, url: braintree_checkout_path(@reservation) , html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: false, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/listings/edit.html.erb
<%= form_for @listings do |f| %>
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>

	<%= f.label :property_type%><br/>
	<%= f.text_field :property_type %><br/>

	<%= f.label :room_number %><br/>
	<%= f.text_field :room_number %><br/>

	<%= f.label :bed_number %><br/>
	<%= f.text_field :bed_number %><br/>

	<%= f.label :guest_number %><br/>
	<%= f.text_field :guest_number %><br/>

	<%= f.label :country %><br/>
	<%= f.text_field :country %><br/>

	<%= f.label :state  %><br/>
	<%= f.text_field :state %><br/>

	<%= f.label :city %><br/>
	<%= f.text_field :city %><br/>

	<%= f.label :zipcode %><br/>
	<%= f.text_field :zipcode %><br/>

	<%= f.label :address %><br/>
	<%= f.text_field :address %><br/>

	<%= f.label :price %><br/>
	<%= f.text_field :price %><br/>

	<%= f.label :description %><br/>
	<%= f.text_field :description %><br/>

	<%= f.label :smoking_allowed %><br/>
	<%= f.text_field :smoking_allowed %><br/>

	<%= f.submit %>
<% end %>

<br/>
<%= image_tag @listings.avatar_url.to_s %>

<%= form_for @listings, :html => {:multipart => true} do |f| %>

  <p>
    <%= f.file_field :avatar %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/listings/index.html.erb
<div class="container">
<button data-toggle="collapse" data-target="#all">All</button>
<button data-toggle="collapse" data-target="#smoking">Smoking allowed</button>

<div id="all" class="collapse">
<table class="table">
<%= paginate @listing %>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Country</th>
      <th scope="col">State</th>
      <th scope="col">City</th>
      <th scope="col">Price</th>
      <th scope="col">Verified</th>
      <th scope="col">Interested?</th>
    </tr>
  </thead>
<tbody>
<% @listing.each do |listing| %>
<tr>
         <td><%= link_to listing.name, listing_path(listing) %></td>
         <td><%= listing.description %></td>
         <td><%= listing.country %></td>
         <td><%= listing.state %></td>
         <td><%= listing.city %></td>
         <td><%= listing.price %></td>
         <td><%= listing.verified %></td>
         <td><%=button_to "Reserve Now", "/listings/#{listing.id}/reservations/new", method: :get %></td>
</tr>
<% end %>
</tbody>
</table>
</div>
    
<div id="smoking" class="collapse">
  <table class="table">
<%= paginate @smoking %>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Country</th>
      <th scope="col">State</th>
      <th scope="col">City</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
<tbody>
<% @smoking.each do |listing| %>
<tr>  
         <td><%= link_to listing.name, listing_path(listing) %></td>
         <td><%= listing.description %></td>
         <td><%= listing.country %></td>
         <td><%= listing.state %></td>
         <td><%= listing.city %></td>
         <td>Price : <%= listing.price %></td>
         <td><%=button_to "Reserve Now", "/listings/#{listing.id}/reservations/new", method: :get %></td>
</tr>
<% end %>
</tbody>
</table>
</div>

</div>  

app/views/listings/new.html.erb
<%= form_for @new_list do |f| %>
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>

	<%= f.label :property_type%><br/>
	<%= f.text_field :property_type %><br/>

	<%= f.label :room_number %><br/>
	<%= f.text_field :room_number %><br/>

	<%= f.label :bed_number %><br/>
	<%= f.text_field :bed_number %><br/>

	<%= f.label :guest_number %><br/>
	<%= f.text_field :guest_number %><br/>

	<%= f.label :country %><br/>
	<%= f.text_field :country %><br/>

	<%= f.label :state  %><br/>
	<%= f.text_field :state %><br/>

	<%= f.label :city %><br/>
	<%= f.text_field :city %><br/>

	<%= f.label :zipcode %><br/>
	<%= f.text_field :zipcode %><br/>

	<%= f.label :address %><br/>
	<%= f.text_field :address %><br/>

	<%= f.label :price %><br/>
	<%= f.text_field :price %><br/>

	<%= f.label :description %><br/>
	<%= f.text_field :description %><br/>

	<%= f.label :smoking_allowed %><br/>
	<%= f.text_field :smoking_allowed %><br/>

	<%= f.submit %>
<% end %> 

app/views/listings/show.html.erb
<h1><%= @listing.name %></h1>
<%= image_tag @listing.avatar_url.to_s %>
<h1><%= @listing.price %></h1>
<%=button_to "Book Now", "/listings/#{@listing.id}/reservations/new", method: :get %>

app/views/reservations/new.html.erb
    <div class="container">
<%= form_for [@listing, @new_reservation] do |f| %>
    <div class='col-md-5'>
        <div class="form-group">
                <%= f.label :check_in %>
            <div class='input-group date' style="position: relative;">
                <input type='text' class="form-control" id='datetimepicker6' name="reservation[check_in]" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class='col-md-5'>
        <div class="form-group">
                <%= f.label :check_out %>
            <div class='input-group date' style="position: relative;">
                <input type='text' class="form-control" id='datetimepicker7' name="reservation[check_out]" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>

<%= f.submit %>
<% end %> 
</div>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false //Important! See issue #1075
        });
        $('#datetimepicker7').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function(e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function(e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>My Listings</h1>
<% @user_listing.each do |x| %>
	<%= link_to x.name, listing_path(x) %><br/>
	<%= button_to "Edit", edit_listing_path(x), method: :get %>
	<%= button_to "Delete", listing_path(x), method: :delete %>
<% end %>

<br/>
<h1>My Reservations</h1>
	<% @user_reservation.each do |y|%>
		Reservation for <%= y.listing.name %><br/>
		Check in date : <%= y.check_in %><br/>
		Check out date : <%= y.check_out %><br/>
		By : <%=  %><br/>
	<% end %>

<br/>
<h1>My Listing Reservation</h1>
<% @user_listing.each do |t| %>
	<%=t.name %><br/>	
		<% t.reservations.each do |m| %>
			<%= m.check_in %><br/>
			<%= m.check_out %><br/>
		<% end %>
<% end %>

<br/>

<%= image_tag current_user.avatar_url.to_s, :class => "shovatar" %>

<%= form_for @user, :html => {:multipart => true} do |f| %>

  <p>
    <%= f.file_field :avatar %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/welcome/index.html.erb
<%= button_to "Sign in with Facebook", "/auth/facebook" %>