config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  root 'welcome#index'
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :create, :update]

  resources :listings do
  resources :reservations 
  end
  # post "/admin/user/:id/listings" => "listing#admin_create", as: admin_listing
  resources :admin, only: [:index, :show]

  get  "/reservations/:id/braintree/new" => "braintree#new", as: "braintree_new"
  post "/reservations/:id/braintree/checkout" => "braintree#checkout", as: "braintree_checkout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :users
	has_many :reservations
	has_many :users, through: :reservation
	mount_uploader :avatar, AvatarUploader
end

app/models/listings_user.rb
class ListingsUser < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  	belongs_to :user
  	belongs_to :listing

  	validate :overlap?, on: :create

    def duration
      (self.check_out - self.check_in).to_i
    end

    def total_price
      self.duration * self.listing.price
    end

  	private
  	def overlap?
  		self.listing.reservations.each do |x|
  			i = (x.check_in..x.check_out).to_a
  			o = (check_in..check_out).to_a	
  			unless (i & o).empty?	
  				errors.add(:overlap, "overlap")
  				break
  			end
  		end
	end
end

app/models/user.rb
Clearance::User

class User < ApplicationRecord
  include Clearance::User
 has_many :authentications, dependent: :destroy
 has_many :listings
 has_many :reservations

  mount_uploader :avatar, AvatarUploader
 
 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     email: auth_hash["extra"]["raw_info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab fb_token to access Facebook for user data
 def fb_token
   x = self.authentications.find_by(provider: 'facebook')
   return x.token unless x.nil?
 end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_user
	before_action :check_admin
	def index
		@listing = Listing.all
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def check_user
		if !current_user
		redirect_to root_path, notice: "No trespassing. "
		end
	end

	def check_admin
		if !current_user.admin
		redirect_to root_path, notice: "No trespassing."
		end
	end
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	@reservation = Reservation.find(params[:id])
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
  @reservation = Reservation.find(params[:id])

  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => @reservation.total_price,
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    redirect_to "/users/#{current_user.id}", :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :check_user
	before_action :check_admin
	def index
		@listing = Listing.order(:name).page(params[:page])
		@smoking = Listing.where(smoking_allowed:true).page(params[:page])
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def new
		@new_list = current_user.listings.new
	end	

	def create
		@new_list = current_user.listings.new(allowed_params)
			if @new_list.save
				redirect_to "/users/#{current_user.id}"
			else
				render "new"
			end
	end

	def edit
		@listings = Listing.find(params[:id])	
	end

	def update
		@listings = Listing.find(params[:id])
			if @listings.update_attributes(allowed_params)
			@listings.update(edit_params)
				redirect_to "/users/#{current_user.id}"
			else
				render "new"
			end		
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy	
		redirect_to "/users/#{current_user.id}"
	end

	private
		def allowed_params
		params.require(:listing).permit(:name, :property_type, :room_number, :bed_number, :guest_number, :country, :state, :city, :zipcode, :address, :price, :description, :user_id, :smoking_allowed, :avatar)
		end

	private
		def edit_params
		params.require(:listing).permit(:avatar)
		end

	def check_user
		if !current_user
			flash[:notice] = "Sorry, please sign in to continue!"
			redirect_to sign_in_path
		end 
	end

	def check_admin
		if current_user.admin
			redirect_to admin_index_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    authentication.update_token(auth_hash)
    @next = root_url
    @notice = "Signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    @next = edit_user_path(user)
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to @next, :notice => @notice
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@user_listing = @user.listings
		@user_reservation = @user.reservations
	end

	def create
	end

	def update
		@user = User.find(params[:id])
		@user.update(edit_params)
		redirect_to @user
	end

	private
	def edit_params
		params.require(:user).permit(:avatar)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<% @listing.each do |listing| %>
	<br/><%= link_to listing.name, admin_index_path(listing) %><br/>
  		<%= listing.description %><br/>
  		<%= listing.country %>
  		<%= listing.state %>
  		<%= listing.city %><br/>
  		Price : <%= listing.price %><br/>

  		<%= form_for listing do |j| %>
  			<%= j.label :verified%><br/>
			<%= j.text_field :verified %><br/>
			<%= j.submit %>
  		<% end %> 
 
<% end %>

app/views/admin/show.html.erb
<h1><%= @listing.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tag %>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
<% if signed_in? %>
<%= image_tag current_user.avatar_url.to_s, :class => "pavatar" %>
<% end %>
  <a class="navbar-brand" href="/">PairBnb</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <a class="nav-item nav-link active" href="/listings">Listings<span class="sr-only">(current)</span></a>
    <% if signed_in? %>
      <a class="nav-item nav-link" href="/listings/new">New Listing</a>
      <a class="nav-item nav-link" data-method="get" href= "/users/<%= current_user.id %>" >My Page</a>
      <a class="nav-item nav-link" data-method="delete" href="/sign_out">Sign Out</a>
      <!-- <%= link_to "Sign Out", sign_out_path, method: :delete, class: "nav-item nav-link" %> -->
      <% else -%>
      <a class="nav-item nav-link" data-method="get" href="/sign_in">Sign In</a>
      <a class="nav-item nav-link" data-method="get" href="/auth/facebook">Sign In With Facebook</a>
    <% end %>  

    </div>
  </div>

</nav>  

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>